/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    CreateMerchantDto: {
      name: string;
      registrationType?: "PERSONAL" | "JURISTIC";
      email: string;
      password: string;
      fullName: string;
      phone: string;
    };
    BankAccount: {
      id: string;
      bankId: string;
      name: string;
      holderName: string;
      accountNumber: string;
      citizenId: string;
      merchant: components["schemas"]["Merchant"];
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    Variant: {
      id: string;
      name: string;
      quantity: number;
      inCompleteQuantity: number;
      completedQuantity: number;
      product: components["schemas"]["Product"];
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    ShippingOverride: { [key: string]: any };
    Product: {
      id: string;
      merchant: components["schemas"]["Merchant"];
      name: string;
      description: string;
      category: string[];
      imageUrls: string[];
      originalPrice: number;
      partyPrice: number;
      partyQuantity: number;
      hasVariants: boolean;
      variants: components["schemas"]["Variant"][];
      shippingIds: string[];
      shippingOverride: components["schemas"]["ShippingOverride"];
      status: "SHOW" | "HIDE";
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    Merchant: {
      id: string;
      registrationType: "PERSONAL" | "JURISTIC";
      name: string;
      email: string;
      authId: string;
      logoUrl: string;
      coverImageUrl: string;
      bannerUrls: string[];
      address: components["schemas"]["Address"];
      bankAccount: components["schemas"]["BankAccount"];
      products: components["schemas"]["Product"][];
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    Address: {
      id: string;
      name: string;
      phone: string;
      address: string;
      merchant: components["schemas"]["Merchant"];
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    PointerDto: { id: string };
    UpdateMerchantDto: {
      name?: string;
      logoUrl?: string;
      coverImageUrl?: string;
      bannerUrls?: string[];
      address?: components["schemas"]["PointerDto"];
      bankAccount?: components["schemas"]["PointerDto"];
    };
    CreateVariantDto: { name: string; quantity: number };
    ShippingOverrideDto: { [key: string]: any };
    CreateProductDto: {
      name: string;
      description: string;
      category: string[];
      imageUrls: string[];
      originalPrice: number;
      partyPrice: number;
      partyQuantity: number;
      hasVariants: boolean;
      variants: components["schemas"]["CreateVariantDto"][];
      shippingIds: string[];
      shippingOverride: components["schemas"]["ShippingOverrideDto"];
      status: "SHOW" | "HIDE";
    };
    UpdateVariantDto: { id?: string; name?: string; quantity?: number };
    UpdateProductDto: {
      name?: string;
      description?: string;
      category?: string[];
      imageUrls?: string[];
      originalPrice?: number;
      partyPrice?: number;
      partyQuantity?: number;
      hasVariants?: boolean;
      variants?: components["schemas"]["UpdateVariantDto"][];
      shippingIds?: string[];
      shippingOverride?: components["schemas"]["ShippingOverrideDto"];
      status?: "SHOW" | "HIDE";
    };
    CreateAddressDto: { name: string; phone: string; address: string };
    UpdateAddressDto: { name?: string; phone?: string; address?: string };
    CreateBankAccountDto: {
      bankId: string;
      name: string;
      holderName: string;
      citizenId: string;
      accountNumber: string;
    };
    UpdateBankAccountDto: {
      bankId?: string;
      name?: string;
      holderName?: string;
      citizenId?: string;
      accountNumber?: string;
    };
    Shipping: {
      id: string;
      name: string;
      cost: number;
      status: "SHOW" | "HIDE";
      merchant: components["schemas"]["Merchant"];
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    CreateShippingDto: { name: string; cost: number; status?: "SHOW" | "HIDE" };
    UpdateShippingDto: {
      name?: string;
      cost?: number;
      status?: "SHOW" | "HIDE";
    };
    ProductSnapshotDto: {
      id: string;
      name: string;
      description: string;
      imageUrls: string[];
      originalPrice: number;
      partyPrice: number;
      partyQuantity: number;
      hasVariants: boolean;
    };
    VariantSnapshotDto: { id: string; name: string };
    ShippingSnapshotDto: { id: string; name: string; cost: number };
    BuyerSnapshot: { id: string; displayName: string; avatarUrl?: string };
    Order: {
      id: string;
      code: string;
      partyId: string;
      transactionId: string;
      productSnapshot: components["schemas"]["ProductSnapshotDto"];
      variantSnapshot: components["schemas"]["VariantSnapshotDto"];
      shippingSnapshot: components["schemas"]["ShippingSnapshotDto"];
      buyerSnapshot: components["schemas"]["BuyerSnapshot"];
      shippingAddress: string;
      price: number;
      quantity: number;
      discount: number;
      fee: number;
      subTotal: number;
      grandTotal: number;
      trackingNumber: string;
      sellerNote: string;
      buyerNote: string;
      paymentMethod: string;
      withdrawal: components["schemas"]["Withdrawal"];
      status: "CANCELLED" | "OPEN" | "DELIVERING" | "RETURNING" | "COMPLETED";
      merchant: components["schemas"]["Merchant"];
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    BankAccountSnapshotDto: {
      id: string;
      bankId: string;
      name: string;
      holderName: string;
      accountNumber: string;
      citizenId: string;
    };
    WithdrawalBatch: {
      id: string;
      merchant: components["schemas"]["Merchant"];
      withdrawals: components["schemas"]["Order"][];
      grandTotal: number;
      bankAccountSnapshot: components["schemas"]["BankAccountSnapshotDto"];
      status: "PENDING" | "PROCESSING" | "FAILED" | "COMPLETED";
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    Withdrawal: {
      id: string;
      merchant: components["schemas"]["Merchant"];
      order: components["schemas"]["Order"];
      batch: components["schemas"]["WithdrawalBatch"];
      status: "READY" | "PENDING" | "PROCESSING" | "FAILED" | "COMPLETED";
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    BuyerSnapshotDto: { id: string; displayName?: string; avatarUrl?: string };
    CreateOrderDto: {
      partyId: string;
      transactionId: string;
      shippingAddress: string;
      productSnapshot: components["schemas"]["ProductSnapshotDto"];
      variantSnapshot: components["schemas"]["VariantSnapshotDto"];
      shippingSnapshot: components["schemas"]["ShippingSnapshotDto"];
      buyerSnapshot: components["schemas"]["BuyerSnapshotDto"];
      price: number;
      quantity: number;
      buyerNote?: string;
    };
    CreateManyOrdersDto: { orders: components["schemas"]["CreateOrderDto"][] };
    UpdateOrderDto: {
      sellerNote?: string;
      trackingNumber?: string;
      status?: "CANCELLED" | "OPEN" | "DELIVERING" | "RETURNING" | "COMPLETED";
    };
    Balance: {
      id: string;
      withdrawable: number;
      pending: number;
      completed: number;
      merchant: components["schemas"]["Merchant"];
      createdAt: string;
      modifiedAt: string;
      deletedAt: string;
    };
    UploadImagesDto: { files: string[] };
    MailDto: { contact: string };
    UpdateWithdrawalBatchDto: {
      status: "PENDING" | "PROCESSING" | "FAILED" | "COMPLETED";
    };
    UpdateOrderForAppDto: {
      status?: "CANCELLED" | "OPEN" | "DELIVERING" | "RETURNING" | "COMPLETED";
    };
  };
}

export type CreateMerchantDto = components['schemas']['CreateMerchantDto']

export type BankAccount = components['schemas']['BankAccount']

export type Variant = components['schemas']['Variant']

export type ShippingOverride = components['schemas']['ShippingOverride']

export type Product = components['schemas']['Product']

export type Merchant = components['schemas']['Merchant']

export type Address = components['schemas']['Address']

export type PointerDto = components['schemas']['PointerDto']

export type UpdateMerchantDto = components['schemas']['UpdateMerchantDto']

export type CreateVariantDto = components['schemas']['CreateVariantDto']

export type ShippingOverrideDto = components['schemas']['ShippingOverrideDto']

export type CreateProductDto = components['schemas']['CreateProductDto']

export type UpdateVariantDto = components['schemas']['UpdateVariantDto']

export type UpdateProductDto = components['schemas']['UpdateProductDto']

export type CreateAddressDto = components['schemas']['CreateAddressDto']

export type UpdateAddressDto = components['schemas']['UpdateAddressDto']

export type CreateBankAccountDto = components['schemas']['CreateBankAccountDto']

export type UpdateBankAccountDto = components['schemas']['UpdateBankAccountDto']

export type Shipping = components['schemas']['Shipping']

export type CreateShippingDto = components['schemas']['CreateShippingDto']

export type UpdateShippingDto = components['schemas']['UpdateShippingDto']

export type ProductSnapshotDto = components['schemas']['ProductSnapshotDto']

export type VariantSnapshotDto = components['schemas']['VariantSnapshotDto']

export type ShippingSnapshotDto = components['schemas']['ShippingSnapshotDto']

export type BuyerSnapshot = components['schemas']['BuyerSnapshot']

export type Order = components['schemas']['Order']

export type BankAccountSnapshotDto = components['schemas']['BankAccountSnapshotDto']

export type WithdrawalBatch = components['schemas']['WithdrawalBatch']

export type Withdrawal = components['schemas']['Withdrawal']

export type BuyerSnapshotDto = components['schemas']['BuyerSnapshotDto']

export type CreateOrderDto = components['schemas']['CreateOrderDto']

export type CreateManyOrdersDto = components['schemas']['CreateManyOrdersDto']

export type UpdateOrderDto = components['schemas']['UpdateOrderDto']

export type Balance = components['schemas']['Balance']

export type UploadImagesDto = components['schemas']['UploadImagesDto']

export type MailDto = components['schemas']['MailDto']

export type UpdateWithdrawalBatchDto = components['schemas']['UpdateWithdrawalBatchDto']

export type UpdateOrderForAppDto = components['schemas']['UpdateOrderForAppDto']